name: 'Hello World'

on:
    push: 
      branches:
        - main
      paths-ignore:
        - .github/**
    pull_request:
      branches:
        - main
    schedule:
      - cron: '15 6 * * 0'
    workflow_dispatch:
      inputs:
        who-to-greet:
          description: 'Who to greet'
          required: true
          default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run Hello World Docker container
        uses: carolyn-sun/ActionsFundamentals@main
        with:
          args: ${{ inputs.who-to-greet }}
